chore: set up prettier rc file for consistent code styling
space-hopper/spacehopper pull request #12
Opened 2021-06-15 20:39 UTC by DevKarenC

2021-06-15 21:53 UTC, jo-z requested changes
can we use tabs instead of spaces? technically more accessable

2021-06-15 22:02 UTC, lemkey approved these changes

2021-06-15 22:46 UTC, DevKarenC commented
> can we use tabs instead of spaces? technically more accessable

sure - can you give me an example?

2021-06-16 22:06 UTC, laura177 approved these changes

2021-06-16 22:38 UTC, jo-z approved these changes

2021-06-16 22:39 UTC, merged